# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-08 07:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20170126_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='start_date_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 8, 7, 27, 34, 119713), null=True, verbose_name=b'Start Date and Time of the quiz'),
        ),
    ]
